let books = [
    {
        id : "0",
        title : "Les Misérables",
        author : "Victor Hugo",
        price : 14.95,
        category : "Drame",
        releaseDate : new Date("1862,11,22"),
        nbSales : 395,
        nbStock: 0,
        cover: "images/lesmiserables.jpg",
        note: 5,
    },
    {
        id : "1",
        title : "Fight Club",
        author : "Chuck Palahniuk",
        price : 9.95,
        category : "Drame",
        releaseDate : new Date("1996,01,14"),
        nbSales : 365,
        nbStock: 237,
        cover: "images/fightClub.jpg",
        note: 4,
    },
    {
        id : "2",
        title : "L'étranger",
        author : "Albert Camus",
        price : 14.95,
        category : "Roman",
        releaseDate : new Date("1996,01,14"),
        nbSales : 345,
        nbStock: 237,
        cover: "images/Letranger.jpg",
        note: 3,
    },
    {
        id : "3",
        title : "Les Fleures du mal",
        author : "Charles Baudelaire",
        price : 19.95,
        category : "Poésie",
        releaseDate : new Date("1857,04,15"),
        nbSales : 598,
        nbStock: 206,
        cover: "images/lesFleursDuMal.jpg",
        note: 4,
    },
    {
        id : "4",
        title : "Le petit prince",
        author : "Antoine de Saint-Exupéry",
        price : 7.99 ,
        category : "Roman",
        releaseDate : new Date("1943,07,15"),
        nbSales : 523,
        nbStock: 68,
        cover: "images/lePetitPrince.jpg",
        note: 4,
    },
    {
        id : "5",
        title : "Cyrano de Bergerac",
        author : "Edmond Rostand",
        price : 22.5,
        category : "Théâtre",
        releaseDate : new Date("1897,09,20"),
        nbSales : 361,
        nbStock: 109,
        cover: "images/cyranoDeBergerac.jpg",
        note: 3,
    },
    {
        id : "6",
        title : "Voyage au bout de la nuit",
        author : "Louis-Ferdiand Céline",
        price : 15.7,
        category : "Roman",
        releaseDate : new Date("1932,12,03"),
        nbSales : 371,
        nbStock: 26,
        cover: "images/voyageAuBout.jpg",
        note: 2,
    },
    {
        id : "7",
        title : "Bel-ami",
        author : "Guy de Maupassant",
        price : 25.5,
        category : "Roman",
        releaseDate : new Date("1885,02,06"),
        nbSales : 230,
        nbStock: 45,
        cover: "images/belAmi.jpg",
        note: 3,
    },
    {
        id : "8",
        title : "Antigone",
        author : "Jean Anouilh",
        price : 12.7,
        category : "Roman",
        releaseDate : new Date("1944,12,03"),
        nbSales : 171,
        nbStock: 0,
        cover: "images/Antigone.jpg",
        note: 2,
    },
    {
        id : "9",
        title : "Alice aux pays des merveilles",
        author : "Lewis Caroll",
        price : 9.5,
        category : "Roman",
        releaseDate : new Date("1974,12,21"),
        nbSales : 300,
        nbStock: 100,
        cover: "images/Alice.jpg",
        note: 5,
    },
    {
        id : "10",
        title : "Frankenstein",
        author : "Mary Shelley",
        price : 20.5,
        category : "Fantastique",
        releaseDate : new Date("2009,10,21"),
        nbSales : 500,
        nbStock: 182,
        cover: "images/Frankenstein.jpg",
        note: 5,
    },
    {
        id : "11",
        title : "Le seigneur des anneaux",
        author : "J.R.R Tolkien",
        price : 40.5,
        category : "Fantastique",
        releaseDate : new Date("1990,09,11"),
        nbSales : 556,
        nbStock: 122,
        cover: "images/leSeigneur.jpg",
        note: 5,
    },
];